name: CoupleScript CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential nasm

    - name: Build CoupleScript
      run: make all

    - name: Create examples
      run: make examples

    - name: Run tests
      run: make test
